name: Perform Mixeway Scan
on:
  push:
    branches:
       - '*'
jobs:
  mixeway-scan:
    name: Mixeway Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo 
          ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse HEAD)"
      - name: Prepare Mixeway docker image
        run: |
          docker pull mixeway/scanner:latest
      - name: Run Scan
        run: |
          docker run -e OSS_USERNAME=$OSS_USERNAME -e OSS_KEY=$OSS_KEY -e MIXEWAY_URL=https://hub.mixeway.io -e MIXEWAY_KEY=$MIXEWAY_KEY -e MIXEWAY_PROJECT_ID=92 -e MODE=STANDALONE -e MIXEWAY_PROJECT_NAME="S01132993_lab_secure_app" -e COMMIT_ID=test -e BRANCH=master -v /opt/lab_sec_audit/sast:/opt/sources mixeway/scanner:latest
